### ISSUE TITLE
Device Type not updating some fields

### ISSUE THREAD

**Issue by beano38** [brandomando/netbox_devicetype_template_playbook#7]
In your task "Build device template in Netbox", you're not checking parent/child status. Also no matter what I put for u_height it sets it as 1, and is_full_depth is always set to true as well.

Here are two device types it will not load correctly for child/parent

```
---
manufacturer: Cisco
model: C3KX-NM-1G
slug: c3kx-nm-1g
part_number: C3KX-NM-1G
u_height: 0
subdevice_role: child
interfaces:
  - name: GigabitEthernet1/1
    type: 1000base-x-sfp
  - name: GigabitEthernet1/2
    type: 1000base-x-sfp
  - name: GigabitEthernet1/3
    type: 1000base-x-sfp
  - name: GigabitEthernet1/4
    type: 1000base-x-sfp
```
```
---
manufacturer: Cisco
model: WS-C3560X-48T-S
slug: ws-c3560x-48T-s
part_number: WS-C3560X-48T-S
is_full_depth: False
u_height: 1
subdevice_role: parent
console-ports:
  - name: con 0
    type: rj-45
power-ports:
  - name: Power Supply 0
    type: iec-60320-c14
  - name: Power Supply 1
    type: iec-60320-c14
interfaces:
  - name: FastEthernet0
    type: 100base-tx
    mgmt_only: true
  - name: GigabitEthernet0/1
    type: 1000base-t
  - name: GigabitEthernet0/2
    type: 1000base-t
  - name: GigabitEthernet0/3
    type: 1000base-t
  - name: GigabitEthernet0/4
    type: 1000base-t
  - name: GigabitEthernet0/5
    type: 1000base-t
  - name: GigabitEthernet0/6
    type: 1000base-t
  - name: GigabitEthernet0/7
    type: 1000base-t
  - name: GigabitEthernet0/8
    type: 1000base-t
  - name: GigabitEthernet0/9
    type: 1000base-t
  - name: GigabitEthernet0/10
    type: 1000base-t
  - name: GigabitEthernet0/11
    type: 1000base-t
  - name: GigabitEthernet0/12
    type: 1000base-t
  - name: GigabitEthernet0/13
    type: 1000base-t
  - name: GigabitEthernet0/14
    type: 1000base-t
  - name: GigabitEthernet0/15
    type: 1000base-t
  - name: GigabitEthernet0/16
    type: 1000base-t
  - name: GigabitEthernet0/17
    type: 1000base-t
  - name: GigabitEthernet0/18
    type: 1000base-t
  - name: GigabitEthernet0/19
    type: 1000base-t
  - name: GigabitEthernet0/20
    type: 1000base-t
  - name: GigabitEthernet0/21
    type: 1000base-t
  - name: GigabitEthernet0/22
    type: 1000base-t
  - name: GigabitEthernet0/23
    type: 1000base-t
  - name: GigabitEthernet0/24
    type: 1000base-t
  - name: GigabitEthernet0/25
    type: 1000base-t
  - name: GigabitEthernet0/26
    type: 1000base-t
  - name: GigabitEthernet0/27
    type: 1000base-t
  - name: GigabitEthernet0/28
    type: 1000base-t
  - name: GigabitEthernet0/29
    type: 1000base-t
  - name: GigabitEthernet0/30
    type: 1000base-t
  - name: GigabitEthernet0/31
    type: 1000base-t
  - name: GigabitEthernet0/32
    type: 1000base-t
  - name: GigabitEthernet0/33
    type: 1000base-t
  - name: GigabitEthernet0/34
    type: 1000base-t
  - name: GigabitEthernet0/35
    type: 1000base-t
  - name: GigabitEthernet0/36
    type: 1000base-t
  - name: GigabitEthernet0/37
    type: 1000base-t
  - name: GigabitEthernet0/38
    type: 1000base-t
  - name: GigabitEthernet0/39
    type: 1000base-t
  - name: GigabitEthernet0/40
    type: 1000base-t
  - name: GigabitEthernet0/41
    type: 1000base-t
  - name: GigabitEthernet0/42
    type: 1000base-t
  - name: GigabitEthernet0/43
    type: 1000base-t
  - name: GigabitEthernet0/44
    type: 1000base-t
  - name: GigabitEthernet0/45
    type: 1000base-t
  - name: GigabitEthernet0/46
    type: 1000base-t
  - name: GigabitEthernet0/47
    type: 1000base-t
  - name: GigabitEthernet0/48
    type: 1000base-t
device-bays:
  - name: FRULink Slot 1
```
Here is a device that will always set to u_height=1 and full_depth=true

```
---
manufacturer: Cisco
model: IOS XR 9000V
slug: xr9kv
part_number: XR9KV
u_height: 0
is_full_depth: false
interfaces:
  - name: MgmtEth0/RP0/CPU0/0
    type: 1000base-t
    mgmt_only: true
  - name: Loopback0
    type: virtual
  - name: GigabitEthernet0/0/0/0
    type: 1000base-t
  - name: GigabitEthernet0/0/0/1
    type: 1000base-t
  - name: GigabitEthernet0/0/0/2
    type: 1000base-t
  - name: GigabitEthernet0/0/0/3
    type: 1000base-t
  - name: GigabitEthernet0/0/0/4
    type: 1000base-t
  - name: GigabitEthernet0/0/0/5
    type: 1000base-t
  - name: GigabitEthernet0/0/0/6
    type: 1000base-t
  - name: GigabitEthernet0/0/0/7
    type: 1000base-t
  - name: GigabitEthernet0/0/0/8
    type: 1000base-t
  - name: GigabitEthernet0/0/0/9
    type: 1000base-t
  - name: GigabitEthernet0/0/0/10
    type: 1000base-t
  - name: GigabitEthernet0/0/0/11
    type: 1000base-t
  - name: GigabitEthernet0/0/0/12
    type: 1000base-t
  - name: GigabitEthernet0/0/0/13
    type: 1000base-t
  - name: GigabitEthernet0/0/0/14
    type: 1000base-t
  - name: GigabitEthernet0/0/0/15
    type: 1000base-t
  - name: GigabitEthernet0/0/0/16
    type: 1000base-t
  - name: GigabitEthernet0/0/0/17
    type: 1000base-t
  - name: GigabitEthernet0/0/0/18
    type: 1000base-t
  - name: GigabitEthernet0/0/0/19
    type: 1000base-t
  - name: GigabitEthernet0/0/0/20
    type: 1000base-t
  - name: GigabitEthernet0/0/0/21
    type: 1000base-t
  - name: GigabitEthernet0/0/0/22
    type: 1000base-t
  - name: GigabitEthernet0/0/0/23
    type: 1000base-t
  - name: GigabitEthernet0/0/0/24
    type: 1000base-t
  - name: GigabitEthernet0/0/0/25
    type: 1000base-t
  - name: GigabitEthernet0/0/0/26
    type: 1000base-t
  - name: GigabitEthernet0/0/0/27
    type: 1000base-t
  - name: GigabitEthernet0/0/0/28
    type: 1000base-t
  - name: GigabitEthernet0/0/0/29
    type: 1000base-t
  - name: GigabitEthernet0/0/0/30
    type: 1000base-t
  - name: GigabitEthernet0/0/0/31
    type: 1000base-t
console-ports:
  - name: Console
    type: rj-45
  - name: Aux
    type: rj-45    
```
